#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp pod-babashka-malli /tmp/release
VERSION=$(cat resources/POD_BABASHKA_MALLI_VERSION)

cd /tmp/release

## release binary as zip archive

zip "pod-babashka-malli-$VERSION-$APP_PLATFORM-amd64.zip" pod-babashka-malli

## cleanup

rm pod-babashka-malli
